<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fusion Framework - Admin</title>
    <meta name="description" content="Fusion Framework Admin area.">
</head>
<body>
    <header>
        <h1>Admin Area</h1>
        <?php echo $include('nav'); ?>
    </header>
    <main>
        <?php echo $content; ?>
    </main>
    <footer>
        <p>&copy; 2024-<?php echo date('Y'); ?> <a href="https://webdesignfusion.com">Web Design Fusion</a></p>
    </footer>
</body>
</html>